In [3]:
import numpy as np

In [12]:
def newSVD(A):
    if(np.array_equal(A,A.T)):
        print("Symmetric")
        D,V = np.linalg.eig(A)
        D=np.sqrt(D)
        s=D[np.flip(np.argsort(D))]
        #Reorder the eigenvector columns to match order of singular values
        V=V[:,np.flip(np.argsort(D))]
        #U = A.dot(V)/s
        #return V,s,V #Doesnt Work
        return V,s,V #Works
    else:
        D,V = np.linalg.eig(np.dot(A.T,A))
        D=np.sqrt(D)
        s=D[np.flip(np.argsort(D))]
        #Reorder the eigenvector columns to match order of singular values
        V=V[:,np.flip(np.argsort(D))]
        U = A.dot(V)/s
        return U,s,V

In [13]:
A=np.array([[1,2,3],[2,1,4],[3,4,1]])
print(A)
U,s,V = newSVD(A)
print(U)
print(s)
print(V)
np.dot(U,np.dot(np.diag(s),V.T))

[[1 2 3]
 [2 1 4]
 [3 4 1]]
Symmetric
[[-0.25523155  0.82403773  0.50578521]
 [-0.60130182 -0.54492509  0.58437383]
 [ 0.75716113 -0.15497893  0.63457746]]


C:\Users\Justin\Anaconda2\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """


[       nan        nan 2.65982586]
[[-0.25523155  0.82403773  0.50578521]
 [-0.60130182 -0.54492509  0.58437383]
 [ 0.75716113 -0.15497893  0.63457746]]


array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [14]:
A=np.array([[1,2,3],[2,1,4],[3,4,1],[1,1,1]],dtype=float)
print(A)
U,s,V = newSVD(A)
print(U)
print(s)
print(V)
np.dot(U,np.dot(np.diag(s),V.T))

[[1. 2. 3.]
 [2. 1. 4.]
 [3. 4. 1.]
 [1. 1. 1.]]


IndexError: too many indices for array