# Gaussian Elimination with Partial Pivoting

In [1]:
from scipy import mat, concatenate
import numpy as np

###### Define the matrix to be reduced.

In [2]:
# Initialize the matrix
A = mat('1 -1 2 -1; 2 -2 3 -3; 1 1 1 0; 1 -1 4 3',float)

In [3]:
print(A)
print(len(A))

[[ 1. -1.  2. -1.]
 [ 2. -2.  3. -3.]
 [ 1.  1.  1.  0.]
 [ 1. -1.  4.  3.]]
4


###### Intialize $U$ and the identity matrix, $I$. Note that $I$ will be used to define the permutation matrix, $P$, later in the algorithm. The matrix $P$ will contain the record of the row swaps that occured so that any right-hand side can be permuted for solving the system. This record will get stored in the pind array below.

In [4]:
# Initialization for RREF
U = A.copy()
n = len(U)
I = np.eye(n)
# Permutation indices
pind = np.arange(n)
print(U)

[[ 1. -1.  2. -1.]
 [ 2. -2.  3. -3.]
 [ 1.  1.  1.  0.]
 [ 1. -1.  4.  3.]]


In [5]:
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
pind

array([0, 1, 2, 3])

###### In order to determine the index of the largest element in a column, $\displaystyle\max_{1\le i\le n}|a_{ij}|$, one can use the argmax function; it returns the index of the largest element of an array.

###### Example: in the array [1,3,55,2,4], 55 is clearly the largest element and has index 2.

In [7]:
np.argmax([1,3,55,2,4])

2

###### Here is the index of the largest element in the firs column (column 0). It should be 1 since 2 is the largest element and has column index 2.

In [8]:
r = np.argmax(abs(U[pind[0:],0]))+0
print(r)

1


###### Proceed with the algorithm and store the row swaps (index swaps) in the pind array.

In [9]:
# *********************************************************************************
# Column 0
# *********************************************************************************
# Obtain pivot index
r = np.argmax(abs(U[pind[0:],0]))+0
# Swap indices
temp = pind[r]
pind[r] = 0
pind[0] = temp
# Construct multiplier and perform elimination
m = U[pind[1:],0]/U[pind[0],0]
U[pind[1:],0] = 0  # set entry to 0
U[pind[1:],1:] -= m*U[pind[0],1:]

In [10]:
print(pind)
print(U)

[1 0 2 3]
[[ 0.   0.   0.5  0.5]
 [ 2.  -2.   3.  -3. ]
 [ 0.   2.  -0.5  1.5]
 [ 0.   0.   2.5  4.5]]


In [11]:
# *********************************************************************************
# Column 1
# *********************************************************************************
# Obtain pivot index
r = np.argmax(abs(U[pind[1:],1]))+1
# Swap indices
temp = pind[r]
pind[r] = pind[1]
pind[1] = temp
# Construct multiplier and perform elimination
m = U[pind[2:],1]/U[pind[1],1]
U[pind[2:],1] = 0  # set entry to 0
U[pind[2:],2:] -= m*U[pind[1],2:]

In [12]:
print(pind)
print(U)

[1 2 0 3]
[[ 0.   0.   0.5  0.5]
 [ 2.  -2.   3.  -3. ]
 [ 0.   2.  -0.5  1.5]
 [ 0.   0.   2.5  4.5]]


In [13]:
# *********************************************************************************
# Column 2
# *********************************************************************************
# Obtain pivot index
r = np.argmax(abs(U[pind[2:],2]))+2
# Swap indices
temp = pind[r]
pind[r] = pind[2]
pind[2] = temp
# Construct multiplier and perform elimination
m = U[pind[3:],2]/U[pind[2],2]
U[pind[3:],2] = 0  # set entry to 0
U[pind[3:],3:] -= m*U[pind[2],3:]

###### Construct the permutation matrix, $P$, by reindexing the rows of the iden

In [14]:
print(pind)
print(U)
# Construct permutation matrix
P = I[pind]
print(P)

[1 2 3 0]
[[ 0.   0.   0.  -0.4]
 [ 2.  -2.   3.  -3. ]
 [ 0.   2.  -0.5  1.5]
 [ 0.   0.   2.5  4.5]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


In [15]:
np.dot(P,U)

matrix([[ 2. , -2. ,  3. , -3. ],
        [ 0. ,  2. , -0.5,  1.5],
        [ 0. ,  0. ,  2.5,  4.5],
        [ 0. ,  0. ,  0. , -0.4]])

###### Combine the steps into a single cell and solve Ax = b using Gaussian Elimination with Partial Pivoting

In [16]:
# Initialization for Ax = b solve
# Construct an augmented matrix
b = mat('1;1;1;1')
U = A.copy()
U = np.concatenate((U.T,b.T))
U = U.T
print(U)

[[ 1. -1.  2. -1.  1.]
 [ 2. -2.  3. -3.  1.]
 [ 1.  1.  1.  0.  1.]
 [ 1. -1.  4.  3.  1.]]


In [17]:
# *********************************************************************************
# Column 0
# *********************************************************************************
# Obtain pivot index
r = np.argmax(abs(U[pind[0:],0]))+0
# Swap indices
temp = pind[r]
pind[r] = 0
pind[0] = temp
# Construct multiplier and perform elimination
m = U[pind[1:],0]/U[pind[0],0]
U[pind[1:],0] = 0  # set entry to 0
U[pind[1:],1:] -= m*U[pind[0],1:]
# *********************************************************************************
# Column 2
# *********************************************************************************
# Obtain pivot index
r = np.argmax(abs(U[pind[2:],2]))+2
# Swap indices
temp = pind[r]
pind[r] = pind[2]
pind[2] = temp
# Construct multiplier and perform elimination
m = U[pind[3:],2]/U[pind[2],2]
U[pind[3:],2] = 0  # set entry to 0
U[pind[3:],3:] -= m*U[pind[2],3:]

###### Perform backward substitution. Notice the first step is to permute the matrix $U$ so that it is in the correct order.

In [24]:
U = np.dot(P,U)
y = U[:,-1]
x = 0*y
'Backward Substitution'
n = len(y)-1
for i in range(n,-1,-1):
    s = y[i]
    for j in range(i+1,n+1):
        s += -U[i,j]*x[j]
    x[i] = s/U[i,i]

In [25]:
from scipy.linalg import *
print(x)
print(solve(A,b))

[[-2.5]
 [ 1.5]
 [ 2. ]
 [-1. ]]
[[-2.5]
 [ 1.5]
 [ 2. ]
 [-1. ]]
