In [1]:
import numpy as np

In [13]:
A=np.array([[1,2,3,4],[2,1,4,3],[3,4,2,1],[4,2,3,1]],dtype=float)
np.random.seed(1) #Mirrored Error in Pivot
#np.random.seed(5) # No Error in Pivot
B=np.random.rand(4,4)
C=np.array([[1,4,4,3],[5,2,4,2],[1,1,2,1],[3,2,1,2]],dtype=float)
sys=np.array([[1,2,2],[3,2,1],[1,3,2]], dtype=float)
b=np.array([[11],[10],[10]], dtype=float)
Tester=B

# Partial Pivoting

In [14]:
def myLUPartial(A):
    m,n=A.shape #Limits
    P = np.arange(m) #Permutation vector
    flop=np.zeros((m,m)) #Permutation Matrix
    U=A.copy() #Copy A to not change it
    L=np.eye(m) #Base L matrix
    if(m!=n): #Check Square
        print("NonSquare input")
        return 1
    for c in range(0,n-1): #Loop
        #************************************************
        # Get a copy of L for pivot flopping
        #************************************************
        W=L.copy()
        V=U.copy() #Get a copy of U for pivot flopping
        O=P.copy() #Same for Permutation
        M=np.argmax(np.abs(U[c:,c])) #Find index of largest in SubColumn
        if(M+c!=c): #If index is not current index, Swap for largest  *******************M+c?*************************
            #************************************************
            L[M+c,:]=W[c,:] #Flop L
            L[c,:]=W[M+c,:]
            #************************************************
            U[M+c,:]=V[c,:] #Flop U
            U[c,:]=V[M+c,:]
            P[M+c]=O[c] #Flop P
            P[c]=O[M+c]
        for r in range(int(c+1),m): #Do Elimination 
            d=U[r,c]/U[c,c]
            L[r,c]=d
            U[r,:]=U[r,:]-d*U[c,:]
    for i in range(0,n): #Make Flop Matrix from Perm Vector
        flop[P[i],i]=1
    #************************************************
    # Unflop L
    #************************************************
    L = np.tril(L,k=-1)+np.eye(m)
    return L,U, flop

In [15]:
L,U, flop=myLUPartial(Tester)
print("A=\n",Tester,"\n")
print("L=\n",L,"\n")
print("U=\n",U,"\n")
print("Recombining:")
print(np.matmul(L,U))
print("flop")
print(flop)
print("Swapping")
print(np.matmul(flop,np.matmul(L,U)))
print("-"*65)
print("Error=\n",Tester-np.matmul(flop,np.matmul(L,U)))

A=
 [[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]
 [2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01]] 

L=
 [[ 1.          0.          0.          0.        ]
 [ 0.49026729  1.          0.          0.        ]
 [ 0.95143055 -0.27910764  1.          0.        ]
 [ 0.35191402 -0.30697936  0.45606686  1.        ]] 

U=
 [[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [0.00000000e+00 5.24965896e-01 2.73315190e-02 5.22243738e-01]
 [0.00000000e+00 0.00000000e+00 4.26714131e-01 5.43333273e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.51687404e-01]] 

Recombining:
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]]
flop
